SELECT * FROM autores;
SELECT * FROM editorial;
SELECT * FROM genero;
SELECT * FROM libros;
SELECT * FROM prestamos;
SELECT * FROM usuarios;

INSERT INTO USUARIOS VALUES (4, 'Juan', 'Pérez', 'Av. Los Alamos 123', '+51 987654321', 'M');

describe usuarios;

-- Vista
select * from prestamo_detallado;

-- CREACION DE PROCEDIMIENTO ALMACENADO:
    --ES UN CONJUNTO DE SENTENCIAS
    --ES UN CONJUNTO DE TAREA O TAREAS
    --ES UN CONJUNTO DE PROCESO DE CODIFICACION
    --ES UN CONJUTNO DE INSTRUCCIONES
    
-- SINTAXIS DEL PROCEDIMIENTO ALMACENADO

--CREATE OR REPLACE PROCEDURE NOMBRE_DEL_PROCEDIMIENTO (PAREMETRO IN TIPO_DE_DATO)
--AS
--    NOMBRE_VARIABLE TIPO;
--BEGIN
--    INSTRUCCIONES;
--END;


CREATE PROCEDURE SP_INSERTAR_DATO
AS
BEGIN
    INSERT INTO USUARIOS VALUES (5, 'Lorena', 'Fidel', 'Av. Los Sauces 183', '+51 987654321', 'F');
    COMMIT;
END;

EXECUTE SP_INSERTAR_DATO();
DESCRIBE USUARIOS;

--PROCEDIMIENTO ALMACENADO PARA INSERTAR
CREATE OR REPLACE PROCEDURE SP_INSERTAR_DATO(
    IDUS IN NUMBER, 
    NOMB IN VARCHAR2, 
    APE IN VARCHAR2,
    SEX IN VARCHAR2)
AS
BEGIN
    INSERT INTO USUARIOS (idusuario,nombre,apellido,sexo) VALUES (IDUS, NOMB, APE, SEX);
    COMMIT;
END;


EXECUTE SP_INSERTAR_DATO(7,'Joel', 'Hernandez', 'M');
EXECUTE SP_INSERTAR_DATO(8,'Mayori', 'Soto', 'F');
EXECUTE SP_INSERTAR_DATO(9,'Sayuri', 'Garcia', 'F');



SELECT * FROM usuarios;

--PROCEDIMIENTO ALMACENADO PARA ACTUALIZAR
CREATE PROCEDURE SP_ACTUALIZAR_DATO(
    IDUS IN NUMBER, 
    NOMB IN VARCHAR2, 
    APE IN VARCHAR2,
    DIREC IN VARCHAR2,
    TELE IN VARCHAR2,
    SEX IN VARCHAR2)
AS
BEGIN
    UPDATE USUARIOS SET nombre = NOMB, apellido = APE, direccion = DIREC, telefono = TELE, sexo = SEX 
    WHERE idusuario = IDUS;
    COMMIT;
END;

EXEC sp_actualizar_dato (7,'SANDRA', 'PAZ', 'Av. Los Jazmines', '999633589', 'F');

--PROCEDIMIENTO ALMACENADO PARA ELIMINAR
CREATE PROCEDURE SP_ELIMINAR_DATO(
    IDUS IN NUMBER)
AS
BEGIN
    DELETE FROM USUARIOS
    WHERE idusuario = IDUS;
    COMMIT;
END;

EXEC sp_eliminar_dato (9);
EXEC sp_eliminar_dato (7);
SELECT * FROM usuarios;
